"""Blob store contract for binary media."""

from __future__ import annotations

from typing import Protocol


class BlobStore(Protocol):
    async def put(self, data: bytes, *, mime_type: str) -> str: ...
    async def get(self, uri: str) -> bytes: ...
    async def exists(self, uri: str) -> bool: ...
    async def delete(self, uri: str) -> bool: ...
    async def count(self) -> int: ...
