"""Metadata store contract for the SEMA control layer."""

from __future__ import annotations

from typing import TYPE_CHECKING, Protocol

from Sprout.artifacts.models import Artifact
from Sprout.execution.models import ChangeProposal
from Sprout.task.models import Task, TaskStatus
from Sprout.trajectory.models import Trajectory
from Sprout.workspace.models import Workspace

if TYPE_CHECKING:
    from Sprout.orchestration.models import ExecutionNode


class MetadataStore(Protocol):
    """Persists structured control-layer objects.

    Raw events and large blobs do not belong here. EventStore and BlobStore
    own those responsibilities.
    """

    async def save_workspace(self, workspace: Workspace) -> None: ...
    async def get_workspace(self, workspace_id: str) -> Workspace | None: ...
    async def list_workspaces(self) -> list[Workspace]: ...

    async def save_task(self, task: Task) -> None: ...
    async def get_task(self, task_id: str) -> Task | None: ...
    async def list_tasks(self, workspace_id: str | None = None) -> list[Task]: ...
    async def update_task_status(self, task_id: str, status: TaskStatus) -> None: ...

    async def save_execution_node(self, node: ExecutionNode) -> None: ...
    async def get_execution_node(self, node_id: str) -> ExecutionNode | None: ...
    async def list_execution_nodes(self, task_id: str) -> list[ExecutionNode]: ...

    async def save_artifact(self, artifact: Artifact) -> None: ...
    async def get_artifact(self, artifact_id: str) -> Artifact | None: ...
    async def list_artifacts(self, name: str | None = None) -> list[Artifact]: ...

    async def save_change_proposal(self, proposal: ChangeProposal) -> None: ...
    async def get_change_proposal(self, proposal_id: str) -> ChangeProposal | None: ...
    async def list_change_proposals(self, task_id: str) -> list[ChangeProposal]: ...

    async def save_trajectory_metadata(self, trajectory: Trajectory) -> None: ...
    async def get_trajectory_metadata(self, trajectory_id: str) -> Trajectory | None: ...
